name: dynamic365_api
description: A Dart library for seamless integration with Microsoft Dynamics 365 APIs using OData and OAuth2 authentication.
version: 0.0.1
repository: https://github.com/abdelrhmanMohamedAdly/Dynamic365_Api_Library.git
homepage: https://github.com/abdelrhmanMohamedAdly/Dynamic365_Api_Library.git

environment:
  sdk: ^3.8.1

dependencies:
  http: ^1.1.0
  shared_preferences: ^2.2.2


dev_dependencies:
  lints: ^5.0.0
  test: ^1.24.0
